# Generated by Django 3.2.6 on 2021-11-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
