# Generated by Django 3.2.6 on 2021-11-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_alter_tasklist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
