# Generated by Django 3.2.7 on 2025-02-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_tasklist_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
