services:
  - type: web
    name: django-todolist
    env: python
    repo: https://github.com/JoeDimumbi/Django-Simple-Todolist-App
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn taskmate.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: todolist-db
          property: connectionString
